jobs:
    fixtures_category_csv:
        order: 30
        connector: Data fixtures
        alias:     fixtures_category_csv
        label:     Categories data fixtures
        type:      fixtures
        configuration:
            filePath: categories.csv
            uploadAllowed: true
            delimiter: ;
            enclosure: '"'
            escape: '\'
            circularRefsChecked: true
            uploadAllowed: true

    fixtures_category_yml:
        order: 30
        connector: Data fixtures
        alias:     fixtures_category_yml
        label:     Categories data fixtures
        type:      fixtures
        configuration:
            filePath: categories.yml

    fixtures_attribute_group_yml:
        order: 30
        connector: Data fixtures
        alias:     fixtures_attribute_group_yml
        label:     Attribute groups data fixtures
        type:      fixtures
        configuration:
            filePath: attribute_groups.yml

    fixtures_channel_yml:
        order: 30
        connector: Data fixtures
        alias:     fixtures_attribute_group_yml
        label:     Channels data fixtures
        type:      fixtures
        configuration:
            filePath: channels.yml

    fixtures_group_type_yml:
        order: 30
        connector: Data fixtures
        alias:     fixtures_group_type_yml
        label:     Group types data fixtures
        type:      fixtures
        configuration:
            filePath: group_types.yml

    fixtures_association_type_yml:
        order: 40
        connector: Data fixtures
        alias:     fixtures_association_type_yml
        label:     Associations data fixtures
        type:      fixtures
        configuration:
            filePath: associations.yml

    fixtures_attribute_yml:
        order: 40
        connector: Data fixtures
        alias:     fixtures_attribute_yml
        label:     Attributes data fixtures
        type:      fixtures
        configuration:
            filePath: attributes.yml

    fixtures_family_yml:
        order: 60
        connector: Data fixtures
        alias:     fixtures_family_yml
        label:     Families data fixtures
        type:      fixtures
        configuration:
            filePath: families.yml

    fixtures_group_yml:
        order: 70
        connector: Data fixtures
        alias:     fixtures_group_yml
        label:     Groups data fixtures
        type:      fixtures
        configuration:
            filePath: groups.yml

    fixtures_product_yml:
        order: 80
        connector: Data fixtures
        alias:     fixtures_product_yml
        label:     Product data fixtures
        type:      fixtures
        configuration:
            filePath: products.yml

    fixtures_product_csv:
        order: 80
        connector: Data fixtures
        alias:     fixtures_product_csv
        label:     Product data fixtures
        type:      fixtures
        configuration:
            filePath: products.csv
            delimiter: ;
            enclosure: '"'
            escape: '\'
            enabled: true
            categoriesColumn: categories
            familyColumn: family
            groupsColumn: groups
            realTimeVersioning: true

    fixtures_association_yml:
        order: 90
        connector: Data fixtures
        alias:     fixtures_association_yml
        label:     Associations data fixtures
        type:      fixtures
        configuration:
            filePath: associations.yml

    fixtures_job_yml:
        order: 100
        connector: Data fixtures
        alias:     fixtures_job_yml
        label:     Jobs data fixtures
        type:      fixtures
        configuration:
            filePath: jobs.yml
